-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 21:12:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema BookStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BookStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BookStore` ;
USE `BookStore` ;

-- -----------------------------------------------------
-- Table `BookStore`.`USERTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`USERTYPE` (
  `idUserType` INT NOT NULL,
  `userType` VARCHAR(30) NULL,
  PRIMARY KEY (`idUserType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`STATUS` (
  `idStatus` INT NOT NULL,
  `status` VARCHAR(30) NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`LENDBOOKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`LENDBOOKS` (
  `idLendBook` INT NOT NULL,
  `dateOfTaking` DATE NULL,
  `USER_idUser` INT NOT NULL,
  PRIMARY KEY (`idLendBook`, `USER_idUser`),
  INDEX `fk_LENDBOOKS_USER1_idx` (`USER_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_LENDBOOKS_USER1`
    FOREIGN KEY (`USER_idUser`)
    REFERENCES `BookStore`.`USER` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`USER` (
  `idUser` INT NOT NULL,
  `userName` VARCHAR(30) NULL,
  `password` VARCHAR(30) NULL,
  `dateOfUserApproval` DATE NULL,
  `rating` VARCHAR(30) NULL,
  `USERTYPE_idUserType` INT NOT NULL,
  `STATUS_idStatus` INT NOT NULL,
  `LENDBOOKS_idLendBook` INT NOT NULL,
  PRIMARY KEY (`idUser`, `USERTYPE_idUserType`, `STATUS_idStatus`, `LENDBOOKS_idLendBook`),
  INDEX `fk_USER_USERTYPE1_idx` (`USERTYPE_idUserType` ASC) VISIBLE,
  INDEX `fk_USER_STATUS1_idx` (`STATUS_idStatus` ASC) VISIBLE,
  INDEX `fk_USER_LENDBOOKS1_idx` (`LENDBOOKS_idLendBook` ASC) VISIBLE,
  CONSTRAINT `fk_USER_USERTYPE1`
    FOREIGN KEY (`USERTYPE_idUserType`)
    REFERENCES `BookStore`.`USERTYPE` (`idUserType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_STATUS1`
    FOREIGN KEY (`STATUS_idStatus`)
    REFERENCES `BookStore`.`STATUS` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_LENDBOOKS1`
    FOREIGN KEY (`LENDBOOKS_idLendBook`)
    REFERENCES `BookStore`.`LENDBOOKS` (`idLendBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`USERINFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`USERINFO` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(30) NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(30) NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_USERINFO_USER1`
    FOREIGN KEY (`idUser`)
    REFERENCES `BookStore`.`USER` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`FORM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`FORM` (
  `idForm` INT NOT NULL,
  `submitionDate` DATE NULL,
  `USER_idUser` INT NOT NULL,
  PRIMARY KEY (`idForm`, `USER_idUser`),
  INDEX `fk_FORM_USER1_idx` (`USER_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_FORM_USER1`
    FOREIGN KEY (`USER_idUser`)
    REFERENCES `BookStore`.`USER` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`STATEOFBOOKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`STATEOFBOOKS` (
  `idState` INT NOT NULL,
  `stateOfBooks` VARCHAR(30) NULL,
  PRIMARY KEY (`idState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`BOOKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`BOOKS` (
  `idBook` INT NOT NULL,
  `bookName` VARCHAR(30) NULL,
  `author` VARCHAR(40) NULL,
  `genre` VARCHAR(30) NULL,
  `yearOfPublishing` DATE NULL,
  `isItArchived` VARCHAR(30) NULL,
  PRIMARY KEY (`idBook`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`LENDINFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`LENDINFO` (
  `idLendInfo` INT NOT NULL,
  `LENDBOOKS_idLendBook` INT NOT NULL,
  `BOOKS_idBook` INT NOT NULL,
  PRIMARY KEY (`idLendInfo`, `LENDBOOKS_idLendBook`, `BOOKS_idBook`),
  INDEX `fk_LENDINFO_LENDBOOKS1_idx` (`LENDBOOKS_idLendBook` ASC) VISIBLE,
  INDEX `fk_LENDINFO_BOOKS1_idx` (`BOOKS_idBook` ASC) VISIBLE,
  CONSTRAINT `fk_LENDINFO_LENDBOOKS1`
    FOREIGN KEY (`LENDBOOKS_idLendBook`)
    REFERENCES `BookStore`.`LENDBOOKS` (`idLendBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LENDINFO_BOOKS1`
    FOREIGN KEY (`BOOKS_idBook`)
    REFERENCES `BookStore`.`BOOKS` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`EKSEMPLQRI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`EKSEMPLQRI` (
  `isbnUnikalenNomer` INT NOT NULL,
  `BOOKS_idBook` INT NOT NULL,
  `STATEOFBOOKS_idState` INT NOT NULL,
  PRIMARY KEY (`isbnUnikalenNomer`, `BOOKS_idBook`, `STATEOFBOOKS_idState`),
  INDEX `fk_EKSEMPLQRI_BOOKS1_idx` (`BOOKS_idBook` ASC) VISIBLE,
  INDEX `fk_EKSEMPLQRI_STATEOFBOOKS1_idx` (`STATEOFBOOKS_idState` ASC) VISIBLE,
  CONSTRAINT `fk_EKSEMPLQRI_BOOKS1`
    FOREIGN KEY (`BOOKS_idBook`)
    REFERENCES `BookStore`.`BOOKS` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EKSEMPLQRI_STATEOFBOOKS1`
    FOREIGN KEY (`STATEOFBOOKS_idState`)
    REFERENCES `BookStore`.`STATEOFBOOKS` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`BOOKSSTORED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`BOOKSSTORED` (
  `BOOKS_idBook` INT NOT NULL,
  `total` INT NULL,
  `available` INT NULL,
  `chitalnq` INT NULL,
  PRIMARY KEY (`BOOKS_idBook`),
  CONSTRAINT `fk_BOOKSSTORED_BOOKS1`
    FOREIGN KEY (`BOOKS_idBook`)
    REFERENCES `BookStore`.`BOOKS` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
